traPtitech/Jomon-UI

- src/components/TransactionFilters.vue
- src/components/requestDetail/RequestFiles.vue
- src/components/transactionDetail/EditTransactionForm.vue
- src/mocks/transactions.ts
- src/pages/NewRequestPage.vue
- src/pages/NewTransactionPage.vue
- src/pages/RequestDetailPage.vue
- src/pages/RequestsPage.vue
- src/pages/TransactionDetailPage.vue
- src/pages/TransactionsPage.vue
- src/stores/tag.ts
コンポーネント分けたり
必要ならsince,untilの指定もこのPRでつけちゃえばよさそう
フォームコンポーネントのPRがマージされないとエラー消えないのでそれまで待つ
> トランザクションの詳細ページの修正

- src/components/newRequest/NewRequestTag.vue
- src/components/requestDetail/RequestAmount.vue
- src/components/requests/RequestItem.vue
- src/mocks/requests.ts
- src/pages/NewRequestPage.vue
- src/pages/RequestDetailPage.vue
- src/pages/composables/useNewRequest.ts
- src/pages/composables/useNewTransaction.ts
- src/pages/composables/useRequestDetail.ts
- src/stores/requestDetail.ts
close https://github.com/traPtitech/Jomon-UI/issues/56
- targetごとにamonutを指定する部分はデザインが決まっていないこともあってまだ実装していない
> amountの応急処置

- src/pages/GroupsPage.vue
- src/pages/RequestsPage.vue
close https://github.com/traPtitech/Jomon-UI/issues/54
> request等がないときにナビゲーションバーを表示しない

- src/components/groupDetail/composables/useGroupInformation.ts
- src/components/requestDetail/CommentLog.vue
- src/components/requestDetail/RequestLogs.vue
- src/components/requestDetail/StatusChangeLog.vue
- src/components/requests/RequestItem.vue
- src/components/shared/InputSelect.vue
- src/components/shared/InputSelectTagWithCreation.vue
- src/components/shared/SimpleButton.vue
- src/components/transactionDetail/EditTransactionForm.vue
- src/components/transactions/TransactionItem.vue
- src/consts/consts.ts
- src/lib/apiTypes.ts
- src/lib/date.ts
- src/pages/GroupDetailPage.vue
- src/pages/TransactionDetailPage.vue
- src/pages/composables/useNewRequest.ts
- src/pages/composables/useNewTransaction.ts
- src/pages/composables/useRequestDetail.ts
- src/stores/request.ts
- src/stores/requestDetail.ts
- src/stores/transaction.ts
close https://github.com/traPtitech/Jomon-UI/issues/53
したかも
> interfaceの乱立をちょっとだけ解消

- src/components/groupDetail/composables/useGroupMember.ts
- src/components/groupDetail/composables/useGroupOwner.ts
- src/components/newRequest/NewRequestTag.vue
- src/components/newRequest/NewRequestTargets.vue
- src/components/requestDetail/RequestTitle.vue
- src/components/transactions/TransactionFilters.vue
- src/pages/NewRequestPage.vue
- src/pages/composables/useAdmin.ts
- src/pages/composables/useNewRequest.ts
- src/stores/groupDetail.ts
- src/stores/requestDetail.ts
close https://github.com/traPtitech/Jomon-UI/issues/59, close https://github.com/traPtitech/Jomon-UI/issues/55
やることリスト
> request作成時のrequest.targetsの修正とuser.nameを一部user.idにした

- src/components/groupDetail/GroupName.vue
- src/components/newRequest/NewRequestTargets.vue
- src/components/requests/RequestItem.vue
- src/mocks/requests.ts
https://github.com/traPtitech/Jomon-UI/issues/47
> 細かいところを色々直すやつ

- src/components/shared/InputRadioButton.vue
- src/components/transactionDetail/EditTransactionForm.vue
- src/mocks/transactions.ts
- src/pages/NewTransactionPage.vue
- src/pages/TransactionDetailPage.vue
- src/pages/composables/useNewTransaction.ts
close [UI/issues/44](https://github.com/traPtitech/Jomon-UI/issues/44)
> トランザクションで金額を入力するときにtraPから出るお金かtraPに入るお金かを指定できるように

- src/components/requestDetail/CommentLog.vue
- src/components/requestDetail/RequestLogs.vue
- src/mocks/requests.ts
- src/pages/RequestDetailPage.vue
- src/styles/toast.css
close https://github.com/traPtitech/Jomon-UI/issues/40
> コメントにURLをつける

- src/components/groupDetail/GroupOwners.vue
- src/components/newTransaction/NewTransactionTarget.vue
- src/components/requestDetail/CommentLog.vue
- src/components/requestDetail/RequestTargets.vue
- src/components/requestDetail/StatusChangeLog.vue
- src/components/requests/RequestItem.vue
- src/components/shared/InputText.vue
- src/mocks/admins.ts
- src/mocks/requests.ts
- src/pages/AdminPage.vue
- src/pages/NewTransactionPage.vue
- src/pages/RequestDetailPage.vue
- src/pages/composables/useNewTransaction.ts
- src/stores/user.ts
close https://github.com/traPtitech/Jomon-UI/issues/69, close https://github.com/traPtitech/Jomon-UI/issues/46
> transactionのtargetの入力方法を修正&user.idをuser.nameに変えるやつ

- src/components/requests/RequestFilters.vue
- src/components/transactions/TransactionFilters.vue
- src/pages/NewGroupPage.vue
- src/stores/request.ts
- src/stores/transaction.ts
close https://github.com/traPtitech/Jomon-UI/issues/77
> filterの絞り込み状態をページ遷移後も保存しておく

- src/components/groupDetail/GroupBudget.vue
- src/components/groupDetail/GroupDescription.vue
- src/components/groupDetail/GroupName.vue
- src/components/groupDetail/composables/useGroupInformation.ts
- src/components/shared/SimpleButton.vue
- src/components/transactionDetail/EditTransactionForm.vue
- src/components/transactionDetail/composables/useEditTransation.ts
- src/pages/GroupDetailPage.vue
- src/pages/TransactionDetailPage.vue
https://github.com/traPtitech/Jomon-UI/issues/72
requestはデザイン決まってからなのでgroupとtransactionだけ
> キャンセルボタンの設置

- src/components/groupDetail/GroupBudget.vue
- src/components/groupDetail/GroupDescription.vue
- src/components/groupDetail/GroupName.vue
- src/components/modal/StatusChangeModal.vue
- src/components/shared/InputNumber.vue
- src/components/shared/InputText.vue
- src/components/shared/InputTextarea.vue
- src/components/shared/MarkdownTextarea.vue
- src/components/transactionDetail/EditTransactionForm.vue
- src/pages/NewGroupPage.vue
- src/pages/NewRequestPage.vue
- src/pages/NewTransactionPage.vue
https://github.com/traPtitech/Jomon-UI/issues/81
> ページやモーダルを開いたときに一番上のフォームにフォーカスが当たるように

- src/components/groupDetail/GroupBudget.vue
- src/components/groupDetail/GroupDescription.vue
- src/components/groupDetail/GroupMembers.vue
- src/components/groupDetail/GroupName.vue
- src/components/groupDetail/GroupOwners.vue
- src/components/groupDetail/composables/useDeleteGroup.ts
- src/components/groupDetail/composables/useGroupInformation.ts
- src/components/groupDetail/composables/useGroupMember.ts
- src/components/groupDetail/composables/useGroupOwner.ts
- src/components/modal/StatusChangeModal.vue
- src/components/requestDetail/NewComment.vue
- src/components/requestDetail/RequestFiles.vue
- src/components/requestDetail/ToTransactionButtons.vue
- src/components/requestDetail/composables/useNewComment.ts
- src/components/shared/SimpleButton.vue
- src/components/transactionDetail/EditTransactionForm.vue
- src/components/transactionDetail/composables/useEditTransation.ts
- src/pages/AdminPage.vue
- src/pages/GroupDetailPage.vue
- src/pages/NewGroupPage.vue
- src/pages/NewRequestPage.vue
- src/pages/NewTransactionPage.vue
- src/pages/composables/useNewGroup.ts
- src/pages/composables/useNewRequest.ts
- src/pages/composables/useNewTransaction.ts
- src/pages/composables/useRequestDetail.ts
- src/stores/groupDetail.ts
- src/stores/requestDetail.ts
- src/stores/tag.ts
close https://github.com/traPtitech/Jomon-UI/issues/82
- 送信時にisSendingを使うようにした
- トーストのメッセージ文を少し変えた
> isSendingを使う

- .gitignore
- .vscode/extensions.json
> extensions.jsonを作成

- src/components/shared/InputNumber.vue
- src/components/shared/InputRadioButton.vue
- src/components/shared/InputSelectTagWithCreation.vue
- src/components/shared/InputText.vue
- src/components/shared/InputTextarea.vue
- src/components/shared/MarkdownTextarea.vue
close https://github.com/traPtitech/Jomon-UI/issues/144
> defineModelに書き換え

- .github/dependabot.yml
本当に weekly にしただけ
なぜかフォーマッタで `'` が `"` になってて、そこだけ気になる
> chore: dependabot の interval を weekly に変更

- .github/dependabot.yml
configuration changes
___
- `dependabot.yml`のスケジュール間隔を週次から月次に変更しました。
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>dependabot.yml</strong><dd><code>Dependabotの更新間隔を月次に変更</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/dependabot.yml
- `dependabot.yml`のスケジュール間隔を週次から月次に変更
</details>
</td>
<td><a href="https://github.com/traPtitech/Jomon-UI/pull/265/files#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3 …
> Dependabotの設定いじる

- src/App.vue
- src/components/newRequest/NewRequestTargets.vue
- src/components/newTransaction/NewTransactionTarget.vue
- src/components/shared/SimpleButton.vue
fix: #230
___
enhancement
___
- `SimpleButton` コンポーネントを新たにインポートし、既存のボタンを置き換えました。
- `SimpleButton` コンポーネントに `flex items-center` クラスを追加し、ボタン内の内容を中央に揃えました。
___
<tr>
<td>
<details>
<summary><strong>NewRequestTargets.vue</strong><dd><code>Replace standard button with SimpleButton component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/components/newRequest/NewRequestTargets.vue
<li><code>SimpleButton</code> component imported and used.<br> <li> Replaced standard button with <code>SimpleButton</code>.<br>
</details>
</td>
<td><a href="https://github.com/traPtitech/Jomon-UI/pull/269/files#diff-f0b9670ab828d455ade3881b223fc848dfa4e45b041 …
> feat/SimpleButton の内容を中央に揃える

- package-lock.json
- package.json
- src/components/shared/InputSelectMultiple.vue
- src/components/transactionDetail/composables/useEditTransation.ts
fix: #186
___
Enhancement, Dependencies
___
- TypeScriptのバージョンを5.5.4から5.6.2に更新し、最新の機能と改善を取り入れました。
- `src/components/shared/InputSelectMultiple.vue`で型ガードを削除し、コードを簡素化しました。
___
<tr>
<td>
<details>
<summary><strong>InputSelectMultiple.vue</strong><dd><code>型ガードの削除によるコードの簡素化</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/components/shared/InputSelectMultiple.vue
- 型ガードを削除し、`filter`関数を簡素化
</details> …
> refactor/typescriptのバージョンを 5.6 にしてfilterの型ガードを消す

- .github/dependabot.yml
あとで戻します
___
enhancement, configuration changes
___
- Dependabotのスケジュールを月次から週次に変更しました。これにより、依存関係の更新がより頻繁に行われるようになります。
- YAMLファイル内のクォートスタイルを一貫性のあるダブルクォートに変更しました。
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>dependabot.yml</strong><dd><code>Update dependabot schedule and quote style</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/dependabot.yml
<li><code>interval</code> for npm package-ecosystem changed from monthly to weekly.<br> <li> Changed quotes from single to double for consistency.<br>
</details>
</td>
<td><a …
> feat: dependabotをweeklyに

- package-lock.json
- public/mockServiceWorker.js
enhancement, dependencies
___
- `public/mockServiceWorker.js`のパッケージバージョンを2.4.9に更新しました。
- `package-lock.json`で複数の依存パッケージのバージョンを更新し、新しいライセンス情報を追加しました。
___
<tr>
<td>
<details>
<summary><strong>mockServiceWorker.js</strong><dd><code>モックサービスワーカーのパッケージバージョン更新</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
public/mockServiceWorker.js
- パッケージバージョンを2.4.8から2.4.9に更新
</details>
</td>
<td><a href="https://github.com/traPtitech/Jomon-UI/pull/318/files#diff-9b67b1 …
> ⬆️ chore: run npm ci, npm audit fix

- src/features/request/model.ts
- src/features/request/repository.ts
- src/stores/request.ts
Enhancement
___
- `RequestQuerySeed` インターフェースに新しいプロパティ `limit` と `offset` を追加しました。
- `fetchRequests` メソッドで `limit` と `offset` を使用してリクエストを送信するように変更しました。
- `defaultParams` に `limit` と `offset` のデフォルト値を設定しました。
___
<tr>
<td>
<details>
<summary><strong>model.ts</strong><dd><code>`RequestQuerySeed` に `limit` と `offset` を追加</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/features/request/model.ts
- 新しいプロパティ `limit` と `offset` を `RequestQuerySeed` インターフェースに追加。
</details>
</td>
<td><a href="https://github.com/traPtitech/Jomon-UI/pull/364/files#diff-9a50b6f8e4b0ab5cb16639935b5b1c54c74ab …
> 🎸 feat: fetchRequest で offset limit を加えて送る

- src/components/groupDetail/GroupBudget.vue
- src/components/groupDetail/GroupDescription.vue
- src/components/groupDetail/GroupMembers.vue
- src/components/groupDetail/GroupName.vue
- src/components/groupDetail/GroupOwners.vue
- src/components/modal/ModalWrapper.vue
- src/components/modal/StatusChangeModal.vue
- src/components/newRequest/NewRequestFileForm.vue
- src/components/newRequest/NewRequestTag.vue
- src/components/newRequest/NewRequestTargets.vue
- src/components/newTransaction/NewTransactionTarget.vue
- src/components/requestDetail/RequestGroup.vue
- src/components/requestDetail/RequestTags.vue
- src/components/requestDetail/RequestTargets.vue
- src/components/shared/InputSelectMultiple.vue
- src/components/shared/InputSelectSingle.vue
- src/features/request/model.ts
- src/features/request/repository.ts
- src/pages/AdminPage.vue
- src/pages/NewGroupPage.vue
- src/pages/NewRequestPage.vue
- src/stores/request.ts
Enhancement
___
- 各コンポーネントおよびページにおいて、見出しとして使用されるタグを適切な`<h2>`タグに変更。
- アクセシビリティとHTMLのセマンティクスを向上させるための修正。
- 対象ファイルはグループ詳細、リクエスト詳細、および新規申請ページ。
___
<tr>
<td>
<details>
<summary><strong>GroupBudget.vue</strong><dd><code>見出しタグを適切な`<h2>`に変更</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/components/groupDetail/GroupBudget.vue
- `<label>`タグを`<h2>`タグに変更し、見出しとして適切なタグを使用。
</details>
</td>
<td><a …
> 💡 refactor: 見出しを順番に付ける

- .vscode/extensions.json
Enhancement
___
- VSCode推奨拡張にTailwind CSSを追加
___
<details> <summary><h3> File Walkthrough</h3></summary>
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>extensions.json</strong><dd><code>Tailwind CSS拡張を推奨リストに追加</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.vscode/extensions.json
- `recommendations`配列に`bradlc.vscode-tailwindcss`を追加
- ファイル末尾に改行を追加
</details>
</td>
<td><a href="https://github.com/traPtitech/Jomon-UI/pull/495/files#diff-c16655a9 …
> chore: extensions.jsonにtailwindcss拡張を追加

- .prettierrc
- src/App.vue
- src/components/applicationDetail/ApplicationAttachment.vue
- src/components/applicationDetail/ApplicationContent.vue
- src/components/applicationDetail/ApplicationFiles.vue
- src/components/applicationDetail/ApplicationTarget.vue
- src/components/applicationDetail/CommentLog.vue
- src/components/applicationDetail/StatusChangeLog.vue
- src/components/applications/ApplicationItem.vue
- src/components/modal/StatusChangeModal.vue
- src/components/navigation/SideDrawer.vue
- src/components/newApplication/NewApplicationFileForm.vue
- src/components/newApplication/NewApplicationTargets.vue
- src/components/partitions/PartitionTable.vue
- src/components/shared/BaseInput.vue
- src/components/shared/EditButton.vue
- src/components/shared/FloatingMenu.vue
- src/components/shared/MarkdownTextarea.vue
- src/components/shared/PaginationBar.vue
- src/components/shared/SearchSelect.vue
- src/components/shared/StatusChip.vue
- src/components/shared/TagsPartition.vue
- src/components/shared/UserIcon.vue
- src/pages/AccountManagerPage.vue
- src/pages/ApplicationDetailPage.vue
- src/pages/ApplicationsPage.vue
- src/pages/NewPartitionPage.vue
- src/pages/NotFoundPage.vue
- src/pages/PartitionDetailPage.vue
- src/pages/PartitionsPage.vue
Enhancement, Configuration
___
- Tailwind CSS クラス順序を統一
- prettier-plugin-tailwindcss を導入
- 既存コンポーネントのクラス整形
- 可読性・一貫性の改善
___
```mermaid
flowchart LR
Prettier["Prettier 設定更新 (.prettierrc)"]
Plugin["prettier-plugin-tailwindcss 追加"]
Files["Vue各コンポーネントのclass属性整形"]
Prettier -- "pluginsに追加・設定" --> Plugin
Plugin -- "class並びを自動ソート" --> Files
```
<details> <summary><h3> File Walkthrough</h3></summary>
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Formatting</strong></td><td><details><summary>29 files</summary><table>
<tr>
<td><strong>App.vue</strong><dd><code>レイアウトクラスの順序最適化</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> chore: prettier-plugin-tailwindcss の導入
